name: simple_smart_scraper
description: A simple smart data scraping library. Data scraping is a technique in which a computer program extract data from human-readable output coming from another program.
version: 1.0.18
author: Edwin Magabe[MagabeLab] <edyma24@gmail.com>
homepage: https://github.com/magabe26/simple_smart_scraper

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: ^1.6.0
  path_provider: ^1.4.5
  rxdart: ^0.23.1
  http: ^0.12.0+2
  petitparser: 2.4.0
  xml: ^3.5.0
  equatable: ^1.0.1
  meta: ^1.1.7

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
